<a href="https://colab.research.google.com/github/HwangHanJae/ml-definitive-guide-pratice/blob/main/make_first_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

붖꽃의 품종 분류(Classification)하기
- 붖꽃 데이터 세트
  - Feature
    - 꽃잎의 길이
    - 꽃잎의 너비
    - 꽃받침의 길이
    - 꽃받침의 너비
  - Label
    - 붖꽃의 품종
      - Setosa
      - Vesicolor
      - Virginica

In [2]:
#sklearn 라이브러리 로드

#붗꽃 데이터 세트 로드
from sklearn.datasets import load_iris
#DecisionTreeClassifier 로드
from sklearn.tree import DecisionTreeClassifier
#훈련데이터, 테스트데이터, 검증데이터 나누는 메서드 로드
from sklearn.model_selection import train_test_split

In [20]:
#붖꽃 데이터 세트에 대하여 알아보기
iris_data = load_iris()

print("load_iris()의 반환결과 : ",type(iris_data))
print("sklearn.utils.Bunch는 딕셔너리와 유사함")

keys = iris_data.keys()
print("붖꽃 데이터 세트의 키들 : ", keys)
#키들이 의미하는 값들

print("\n feature_names 의 type : ", type(iris_data.feature_names))
print(" feature_names 의 shape : ", len(iris_data.feature_names))
print(iris_data.feature_names)

print("\n target_names 의 type : ", type(iris_data.target_names))
print(" target_names 의 shape : ", len(iris_data.target_names))
print(iris_data.target_names)

print("\n data 의 type : ", type(iris_data.data))
print(" data 의 shape : ", iris_data.data.shape)
print(iris_data.data)

print("\n target 의 type : ", type(iris_data.target))
print(" target 의 shape : ", iris_data.target.shape)
print(iris_data.target)

load_iris()의 반환결과 :  <class 'sklearn.utils.Bunch'>
sklearn.utils.Bunch는 딕셔너리와 유사함
붖꽃 데이터 세트의 키들 :  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

 feature_names 의 type :  <class 'list'>
 feature_names 의 shape :  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 type :  <class 'numpy.ndarray'>
 target_names 의 shape :  3
['setosa' 'versicolor' 'virginica']

 data 의 type :  <class 'numpy.ndarray'>
 data 의 shape :  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 

In [5]:
import pandas as pd

#붖꽃 데이터 세트를 로딩
iris = load_iris()

#iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있음

iris_data = iris.data

#iris.target은 붖꽃 데이터 세트에서 label 데이터를 가지고 있음
iris_label = iris.target
print("iris target 값 :", iris_label)
print("iris target 명 : ", iris.target_names)

#붖꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df["label"] = iris.target
iris_df.head(3)

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 :  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0

[3 rows x 5 columns]

setosa : 0

vesicolor : 1

virginica : 2

In [ ]:
#훈련데이터, 테스트데이터 나누기
seed = 11
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=seed)

#DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=seed)