<a href="https://colab.research.google.com/github/HwangHanJae/ml-definitive-guide-pratice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

라이브러리 로드

In [1]:
#라이브러리 로드
import numpy as np

ndarray 확인

In [3]:
#shape 변수로 ndarray의 크기 확인
array1 = np.array([1,2,3])
print("array1 type: ", type(array1))
print("array1 type 형태: ", array1.shape)
print(array1)

array2 = np.array([[1,2,3,],
                   [2,3,4]])

print("array2 type: ", type(array2))
print("array2 type 형태: ", array2.shape)
print(array2)

array3 = np.array([[1,2,3]])

print("array3 type: ", type(array3))
print("array3 type 형태: ", array3.shape)
print(array3)

array1 type:  <class 'numpy.ndarray'>
array1 type 형태:  (3,)
[1 2 3]
array2 type:  <class 'numpy.ndarray'>
array2 type 형태:  (2, 3)
[[1 2 3]
 [2 3 4]]
array3 type:  <class 'numpy.ndarray'>
array3 type 형태:  (1, 3)
[[1 2 3]]


In [ ]:
#각 차원을 ndarray.ndim을 이용해 확인
print("array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [5]:
#dtype 속성으로 확인

list1 = [1,2,3]

print(type(list1))
array1 = np.array(list1)
print()
print(type(array1))
print(array1, array1.dtype)

<class 'list'>

<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
#int, string 리스트, int float 리스트 ndarray로 변경후 데이터 타입 확인
list2 = [1,2,"test"]
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
#int32 type -> float64 type , float64 type -> int32 type

array_int = np.array([1,2,3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)


array_int1 = array_float.astype("int32")
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype("int32")
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray 생성

In [8]:
#arange() 함수 사용 0부터 순차적으로 ndarray 생성
#start, stop 인자값이 존재
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
#zeros(), ones() 함수 사용 
#default float64
zero_array = np.zeros((3,2), dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray reshape

In [10]:
#reshape() : ndarray의 차원의 크기를 변경

#0~9까지의 1차원 ndarray를 2x5, 5x2로 변경

array1 =  np.arange(10)
print("array1\n", array1)

array2 = array1.reshape(2,5)
print("array2\n", array2)

array3 = array1.reshape(5,2)
print("array3\n", array3)

array1
 [0 1 2 3 4 5 6 7 8 9]
array2
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
#가장 보편적으로 사용하는 reshape() 인자값에 -1넣기
array1= np.arange(10)
print("array1 shape : ", array1.shape)
print(array1)
array2 = array1.reshape(-1, 5)
print("array2 shape : ", array2.shape)
print(array2)
array3 = array1.reshape(5,-1)
print("array3 shape : ", array3.shape)
print(array3)

array1 shape :  (10,)
[0 1 2 3 4 5 6 7 8 9]
array2 shape :  (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape :  (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
#reshape(-1,1)
#원본형태가 어떤형태라도 2차원이고 여러개의 로우를 가지되 반드시 1개의 컬럼을 가진
#ndararry로 변환됨을 보장

array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print("array3d shape : ", array3d.shape)
print("array3d:\n", array3d.tolist())
#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n ', array5.tolist())
print("array5 shape:", array5.shape)
#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print("array6:\n", array6.tolist())
print("array6 shape ; ", array6.shape)

array3d shape :  (2, 2, 2)
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
  [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape ;  (8, 1)


ndarray 인덱싱

In [22]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print("array1 : ", array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print("value", value)
print(type(value))

array1 :  [1 2 3 4 5 6 7 8 9]
value 3
<class 'numpy.int64'>


In [24]:
print("array1 : ", array1)
print('맨 뒤의 값:', array1[-1], " 맨 뒤에서 두 번째 값:", array1[-2])

array1 :  [1 2 3 4 5 6 7 8 9]
맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [28]:
#단일 인덱스를 이용해 ndarray 내의 데이터값 수정
array1 = np.arange(1,10)
print("array1 : ", array1)
print("수정전 array1[0] : ", array1[0])
array1[0] = 9
print("수정후 array1[0] : ", array1[0])
print()
print("수정전 array1[8] : ", array1[8])
array1[8] = 0
print("수정후 array1[8] : ", array1[8])
print()
print("array1 : ", array1)

array1 :  [1 2 3 4 5 6 7 8 9]
수정전 array1[0] :  1
수정후 array1[0] :  9

수정전 array1[8] :  9
수정후 array1[8] :  0

array1 :  [9 2 3 4 5 6 7 8 0]


In [34]:
#2차원 ndarray에서의 데이터 접근은 콤마(,)로 분리된
#로우와 칼럼의 위치의 인덱스를 통해 접근

array1d = np.arange(start=1, stop=10)
print("array1d : ", array1d)
array2d = array1d.reshape(3,3)
print("array2d :\n", array2d)

print("(row=0, col=0) index 가리키는 값:", array2d[0,0])
print("(row=0, col=1) index 가리키는 값:", array2d[0,1])
print("(row=1, col=0) index 가리키는 값:", array2d[1,0])
print("(row=2, col=2) index 가리키는 값:", array2d[2,2])

array1d :  [1 2 3 4 5 6 7 8 9]
array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [35]:
#슬라이싱(:) 기호를 이용해 연속한 데이터를 슬라이싱해서 추출
#시작인덱스에서 종료인덱스-1의 위치에 있는 데이터를 반환

array1= np.arange(start=1, stop=10)
print("array1 : ", array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

array1 :  [1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [38]:
# ":" 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
# ":" 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주

array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print("array4 : ", array4)

array5 = array1[3:]
print("array5 : ", array5)

array6 = array1[:]
print("array6 : ", array6)

array4 :  [1 2 3]
array5 :  [4 5 6 7 8 9]
array6 :  [1 2 3 4 5 6 7 8 9]


In [40]:
#2차원 ndarray 슬라이싱(:)
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print("array2d :\n", array2d)

print("array2d[0:2, 0:2] : \n", array2d[0:2, 0:2])
print("array2d[1:3, 0:3] : \n", array2d[1:3, 0:3])
print("array2d[1:3, :] : \n", array2d[1:3, :] )
print("array2d[:, :] : \n", array2d[:, :])
print("array2d[:2, 1:] : \n", array2d[:2, 1:])
print("array2d[:2, 0] : \n", array2d[:2, 0])

array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] : 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] : 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] : 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] : 
 [[2 3]
 [5 6]]
array2d[:2, 0] : 
 [1 4]


In [41]:
#2차원에서 뒤에 오는 인덱스를 없애면 로우 축(axis0)의 첫번째 ndarray를 반환
#3차원에서는 뒤에 오는 인덳를 없애면 2차원 ndarray를 반환
print("array2d : \n", array2d)
print("array2d[0] : ",array2d[0])
print("array2d[1] : ", array2d[1])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0] :  [1 2 3]
array2d[1] :  [4 5 6]


In [45]:
#팬시 인덱싱(Fancy Indexing)은 리스트나 ndarray로 인덱스 집합을 지정
#해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print("array2d : \n", array2d)
print("array2d[[0,1],2] : ",array2d[[0,1], 2])
print("array2d[[0,1],0:2] : \n",array2d[[0,1], 0:2])
print("array2d[[0,1]] : \n ", array2d[[0,1]])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] :  [3 6]
array2d[[0,1],0:2] : 
 [[1 2]
 [4 5]]
array2d[[0,1]] : 
  [[1 2 3]
 [4 5 6]]


In [46]:
#불린 인덱싱(Boolean indexing) 조건 필터링
#불린 인덱싱을 이용하면 for loop / if else 문 보다 훨씬 간단하게 이를 구현
#[]내에 조건문을 그래도 기재

array1d = np.arange(start=1, stop=10)
#[]안에 array1d > 5 Boolean indexing을 적용
print("array1d > 5 불린 인덱싱 결과 값 : ", array1d[array1d > 5])

array1d > 5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [47]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [48]:
boolean_indexes = np.array([False, False, False,False, False,True, True, True, True])
print("불린 인덱스로 필터링 결과 : ", array1d[boolean_indexes])

불린 인덱스로 필터링 결과 :  [6 7 8 9]


In [49]:
indexes = np.array([5,6,7,8])
print("일반 인덱스로 필터링 결과 : ", array1d[indexes])

일반 인덱스로 필터링 결과 :  [6 7 8 9]


행렬의 정렬 - sort(), argsort()

In [51]:
org_array = np.array([3,1,9,5])
print("원본 행렬: ", org_array)
#np.sort()로 정렬
sort_array1= np.sort(org_array)
print("np.sort() 호출 후 반환된 정렬 행렬 : ", sort_array1)
print("np.sort() 호출 후 원본 행렬 : ", org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print("org_array.sort() 호출 후 반환된 행렬 : ", sort_array2)
print("org_array.sort() 호출 후 원본 행렬 : ", org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [57]:
#내림차순 정렬 [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬 : ", sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [58]:
#2차원 행렬 정렬
array2d = np.array([[8, 12],
                    [7, 1]])
print("array2d : \n", array2d)
print()
sort_array2d_axis0 = np.sort(array2d, axis=0)
print("로우 방향으로 정렬 : \n", sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print("칼럼 방향으로 정렬 : \n", sort_array2d_axis1)

array2d : 
 [[ 8 12]
 [ 7  1]]

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


In [60]:
#정렬된 행렬의 인덱스를 반환하기
#np.argsort()이용
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print("행렬 정렬 시 원본 행렬의 인덱스", sort_indices)

행렬 정렬 시 원본 행렬의 인덱스 [1 0 3 2]


In [61]:
#내림차순 정렬시 
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스: ", sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


선형대수 연산 - 행렬 내적과 전치행렬 구하기

In [62]:
#행렬 내적(행렬 곱)
#np.dot() 이용해 계산
#2x3 * 3x2 행렬을 연산하면 2x2행렬이 나옴
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print("행렬 내적 결과 : \n", dot_product)


행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


In [65]:
#전치 행렬
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print("A의 전치 행렬 : \n", transpose_mat)

A의 전치 행렬 : 
 [[1 3]
 [2 4]]
